name: WishWithMe
options:
  bundleIdPrefix: me.wishwith
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.10"
    TARGETED_DEVICE_FAMILY: "1"  # iPhone only
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: ""
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  WishWithMe:
    type: application
    platform: iOS
    sources:
      - path: WishWithMe
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.wishwith.app
        INFOPLIST_KEY_CFBundleDisplayName: "Wish With Me"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.lifestyle"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SWIFT_EMIT_LOC_STRINGS: YES
    info:
      path: WishWithMe/Resources/Info.plist
      properties:
        CFBundleDisplayName: "Wish With Me"
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        ITSAppUsesNonExemptEncryption: false
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains:
            localhost:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
        CFBundleURLTypes:
          - CFBundleURLName: "me.wishwith.app"
            CFBundleURLSchemes:
              - wishwithme
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
    entitlements:
      path: WishWithMe/Resources/WishWithMe.entitlements
      properties:
        com.apple.security.application-groups:
          - group.me.wishwith.app
        keychain-access-groups:
          - $(AppIdentifierPrefix)me.wishwith.app

  WishWithMeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: WishWithMeTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.wishwith.app.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/WishWithMe.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/WishWithMe"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: WishWithMe

schemes:
  WishWithMe:
    build:
      targets:
        WishWithMe: all
        WishWithMeTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - WishWithMeTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
